// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZBPElIsRduTurb-necuLVZkFW4rsXJfE',
    appId: '1:528899770660:web:b45146adbe74355ce0cbb1',
    messagingSenderId: '528899770660',
    projectId: 'market-ile',
    authDomain: 'market-ile.firebaseapp.com',
    storageBucket: 'market-ile.firebasestorage.app',
    measurementId: 'G-K4PJV1DN9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqkhx9EWXk-4O6VI_gx83Kr73uGgsK1E',
    appId: '1:528899770660:android:17936a3dd37b8860e0cbb1',
    messagingSenderId: '528899770660',
    projectId: 'market-ile',
    storageBucket: 'market-ile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWO1d0f63Djr4XQlPIGP7xOGa3JBX2mk',
    appId: '1:528899770660:ios:27aaf4ec78667cf2e0cbb1',
    messagingSenderId: '528899770660',
    projectId: 'market-ile',
    storageBucket: 'market-ile.firebasestorage.app',
    iosBundleId: 'com.example.projetoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaWO1d0f63Djr4XQlPIGP7xOGa3JBX2mk',
    appId: '1:528899770660:ios:27aaf4ec78667cf2e0cbb1',
    messagingSenderId: '528899770660',
    projectId: 'market-ile',
    storageBucket: 'market-ile.firebasestorage.app',
    iosBundleId: 'com.example.projetoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZBPElIsRduTurb-necuLVZkFW4rsXJfE',
    appId: '1:528899770660:web:a7fbc06b3f4a2f78e0cbb1',
    messagingSenderId: '528899770660',
    projectId: 'market-ile',
    authDomain: 'market-ile.firebaseapp.com',
    storageBucket: 'market-ile.firebasestorage.app',
    measurementId: 'G-KGTT48S189',
  );

}